### ISSUE TITLE
Task Out Next Steps

### ISSUE THREAD

**Issue by jackrwoods** [OSU-Sustainability-Office/sustainability_map#1]
The last commit to the Sustainability Map repository was Feb 3. We need to:

- Determine how "production-ready" the map is
- Task out new features & bugfixes
- Create a timeline for release

**Comment by MilanDonhowe** [comment]
I created a quick design doc in the shared drive to start mapping the next steps for the Sustainability Map.  Is the sustainability map expected to come with the ability to add/delete features from the website (e.g. via some login & admin authentication mechanism)?

**Comment by jackrwoods** [comment]
@MilanDonhowe I can imagine that may be a desired feature down the road, but it won't be a part of the initial mvp.
